### ISSUE TITLE
Define behaviour for `CRD` and `ConfigMap` containing the same profile

### ISSUE THREAD

**Issue by pjbgf** [kubernetes-sigs/security-profiles-operator#131]
The operator is gaining [full support](https://github.com/kubernetes-sigs/seccomp-operator/pull/125/) to represent seccomp profiles in `CRD`. 

Used in conjunction, and having the same profile name used in both CRD and ConfigMap forms, may lead to a non-deterministic results. Whatever resource is created last would overwrite the other former. Here's a few ideas on how we could tackle it:

1. Only allow a single method to represent profiles per cluster. When `CRD` is enabled, `ConfigMap` is disabled and vice-versa. 

2. Create slightly different path for each (i.e. `cm/myprofile.json` and `crd/myprofile.json`).

**Comment by pjbgf** [comment]
@cmurphy @saschagrunert @hasheddan any suggestions on other options or favourite options? I personally would be leaning towards the first one.

**Comment by saschagrunert** [comment]
Would be fine having it configurable, while having the CRD be the new default :)

**Comment by cmurphy** [comment]
It might be easier to just use different paths. The path for a profile created as a ConfigMap versus a CRD are already naturally different, since both the name of the ConfigMap and an explicit name for the file are used to construct the path, e.g. `/var/lib/seccomp-operator/<namespace>/<configmap name>/<file name>`, but there is no equivalent explicit file name for the CRD (unless we want to add it), so it would be more straightforward to write them to something like `/var/lib/seccomp-operator/<namespace>/custom-profiles/<resource name>.json`. Then there would only be a collision if a ConfigMap happened to use "custom-profiles" as its name. But I can see arguments for option 1 as well.

**Comment by pjbgf** [comment]
@cmurphy My main concern would be the edge case you already called out, which makes me feel like option 2 may become a footgun as it gives users some room for misinterpretation.

**Comment by pjbgf** [comment]
After some [talk on this subject](https://kubernetes.slack.com/archives/C013FQNB0A2/p1602176399038600?thread_ts=1602163933.038000&cid=C013FQNB0A2) we come to the conclusion that we were better-off removing `ConfigMap` support.

This change will make it easier for users to use the operator and remove unnecessary ambiguity. 
Closing this issue given that its goal was to define the behaviour, which no longer is needed.

/close
